### ISSUE TITLE
Order finalization

### ISSUE THREAD

**Issue by garyfisher** [sakgiok/codwfeeplus#4]
The order can be processed with prestashop debug enabled. If debug is off, nothing happens. What may be the problem ?

Prestashop 1.7.6.1

![image](https://user-images.githubusercontent.com/285517/68850852-0d59a180-06d5-11ea-9923-d4849dcdf26b.png)

**Comment by sakgiok** [comment]
some kind of conflict with any checkout module? Any error output in the logs?
