### ISSUE TITLE
Customization module 

### ISSUE THREAD

**Issue by go-sudo** [sakgiok/codwfeeplus#5]
Hello Sir

I'm on PS 1.7 so I found you module very helpful and I need you help please

I installed the module for propose that it calculate payment in advance so when customer choose this method he will get information that he should pay 10% of the cart in advance 
https://prnt.sc/qmifz9

so I found a solution to do that and I changed the + to - but when I confirm the order the fees are added to the price total so I need you show me how I can remove the product code from the cart validation

```
$total_original = $cart->getOrderTotal(true, Cart::ONLY_PRODUCTS);
        $integration = Configuration::get('SG_CODWFEEPLUS_INTEGRATION_WAY');
        if ($integration == 0) {
            //By condition
            if ($cond_integration == 1 && $CODfee != 0) {
                $this->validate_removeProduct($CODfee, $cart, $customer, $taxrule, $orderstate);
            } else {
                $this->validate_addToCarrier($CODfee, $cart, $customer, $orderstate);
            }
        } elseif ($integration == 2 && $CODfee != 0) {
            $this->validate_removeProduct($CODfee, $cart, $customer, $taxrule, $orderstate);
        } else {
            $this->validate_addToCarrier($CODfee, $cart, $customer, $orderstate);
        }

```

Regards

**Comment by sakgiok** [comment]
You could try and set the $CODfee parameter to 0 just before you call the validation function, or call the original validation function from the Prestashop PaymentModule class and bypass my functions.
Since, this is not what the module is made for, I can't be sure this will work.

**Comment by go-sudo** [comment]
Hello

I appreciate your help, I need just to know where can edit the file where the product is added to total price so I can manage to be deduct from the total price and not added 


![image](https://user-images.githubusercontent.com/11594433/72310850-2524b600-3683-11ea-97f3-5cf09af22f72.png)

Regards
