### ISSUE TITLE
Email sent on purchase

### ISSUE THREAD

**Issue by jperdior** [sakgiok/codwfeeplus#6]
Hello, first of all nice module!
I am having problems to translate the email that is sent after the user buys using COD payment method. 
Basically I am receiving the email for "Awaiting payment by check". The thing is this email its translated already to spanish and anyway we receive it in english. You know what may cause this?

Thanks!

**Comment by sakgiok** [comment]
Hi,
I can't see how this module would interfere with mail translations. Have you tried to set the order state to something different and see if you get the same problem?
