### ISSUE TITLE
Free shiping - free cash on delivery

### ISSUE THREAD

**Issue by KoveZoli** [sakgiok/codwfeeplus#8]
Hi,

If shipping is free, the cost of cash on delivery should also be free.
So I can't set this.
Is this option not in the module?

Thanks!

**Comment by sakgiok** [comment]
Hi,
there is not such an option available. You can add a condition though with the circumstances that make the delivery free of charge.
For instance, if the delivery is free when your cart value is more than 50€, you can add a condition to set the cod fee at 0€ when the cart value is more than 50€.
Make sure to have this condition on the top of the conditions list so it always validates first and set the cod fee to 0€ when the cart value matches (provided that behavior setting is set to "Apply the highest in the list, matching fee").

**Comment by KoveZoli** [comment]
Thanks!
